from __future__ import annotations

from dataclasses import dataclass


@dataclass
class MonitoringOutput:
    """Data class containing the output of the monitoring algorithm
    after one update step over a sample.

    If drift is detected then a drift info data model is present with
    additional information about the drift"""

    drift_detected: bool
    drift_info: DriftInfo | None


@dataclass
class DriftInfo:
    """Data class containing information of the detected drift.
    It is generated by the drift detector.
    """

    feature_index: int
    drift_detector: str
    p_value: float | None = None
    threshold: float | None = None
